### ISSUE TITLE
~/owl/./owl.py --show-display not working on rapi 5 or rpi 3b

### ISSUE THREAD

**Issue by pedro26538** [geezacoleman/OpenWeedLocator#125]
this log is with rpi 5 with rpi cam

(owl) raspi@raspberrypi:~ $ ~/owl/./owl.py --show-display
[INFO] Setting up nozzles...
[INFO] Nozzle setup complete. Initiating camera...
Traceback (most recent call last):
  File "/home/raspi/owl/./owl.py", line 546, in <module>
    owl = Owl(input_file_or_directory=args.input,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspi/owl/./owl.py", line 158, in __init__
    from picamera import PiCameraMMALError
  File "/home/raspi/.virtualenvs/owl/lib/python3.11/site-packages/picamera/__init__.py", line 72, in <module>
    from picamera.exc import (
  File "/home/raspi/.virtualenvs/owl/lib/python3.11/site-packages/picamera/exc.py", line 41, in <module>
    import picamera.mmal as mmal
  File "/home/raspi/.virtualenvs/owl/lib/python3.11/site-packages/picamera/mmal.py", line 49, in <module>
    _lib = ct.CDLL('libmmal.so')
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libmmal.so: cannot open shared object file: No such file or directory

**Comment by geezacoleman** [comment]
Which version of Raspian are you running and what was the install method? The error you're receiving is likely because picamera isn't installed, usually because the OS is Raspbian Bookworm or a recent version, which doesn't support picamera.

This has been fixed over on the [Picamera2](https://github.com/geezacoleman/OpenWeedLocator/tree/picamera2) branch and should be merging it to the main branch this week. Feel free to try out this branch, just make sure to replace the `git clone https://github.com/geezacoleman/OpenWeedLocator` with `git clone -b picamera2 https://github.com/geezacoleman/OpenWeedLocator/tree/picamera2 owl`, otherwise you'll end up with the code from the main branch which won't help.
